### ISSUE TITLE
Issue with reading in char arrays from hdf5 [h5_0.9.4]

### ISSUE THREAD

**Issue by hardingnj** [mannau/h5#22]
Firstly thanks for this really useful package.

I'm getting a really strange issue with h5, it's do to with reading in text fields that have been written from python's h5py. I finally managed to reproduce the error, it's to do with the length of the strings you specify in the numpy dtype. 
A string of max length x is not read in correctly unless you specify the numpy dtype as "|S(x + 1)". 

I create the h5 file in python like so:
https://github.com/hardingnj/Rag1k/blob/master/testing_hdf5_python.ipynb

And read it with:
https://github.com/hardingnj/Rag1k/blob/master/testing_hdf5_R.ipynb

It works fine when I read back in h5py so I suspect it's a issue with h5 the [R] package. I hope that's a reasonable assumption, apologies if not.

**Comment by mannau** [comment]
thanks for reporting - definitely sounds like a bug in h5 for ascii and missing null termination. 
best,
mario

**Comment by hardingnj** [comment]
Hi, just wondering if you would have a workaround you could suggest for this?

**Comment by shabbychef** [comment]
Are the data stored as `H5S_UNLIMITED`?

**Comment by mannau** [comment]
By default: yes.
Depends on the parameters maxdim and compression.
best,
m


Am 22/01/16 um 19:01 schrieb Steven Pav:

**Comment by cyfdecyf** [comment]
I'm having the same problem when reading hdf5 data created with h5py. The pull request is tested on OS X and seems fixes the problem.
