### ISSUE TITLE
Reading datasets with dimensions of size 1 fails

### ISSUE THREAD

**Issue by kthr** [mannau/h5#26]
I have created a very simple h5 file containing three entries:
/multi_integer, /single_integer, /single_char

Trying to read both  /single_integer and /single_char fails with the h5 package version 0.9.4. I guess reading the dimensions for the two entries somehow fails.

[test.h5.zip](https://github.com/mannau/h5/files/156717/test.h5.zip)

**Comment by mannau** [comment]
Already fixed https://github.com/mannau/h5/issues/25. Just install the newest version from github.
