### ISSUE TITLE
list.groups() does not support H5Link

### ISSUE THREAD

**Issue by kthr** [mannau/h5#27]
We are using H5link's in our hdf5 file, I realized that they are not supported yet. I changed the code to add the support and also replaced the deprecated H5Giterate by H5Lvisit and H5Literate. There is now less code needed for group traversal. Hope you can and will use it.

Best,
Konstantin

[add_support_for_h5link.patch.zip](https://github.com/mannau/h5/files/158409/add_support_for_h5link.patch.zip)

**Comment by kthr** [comment]
The patch from my previous comment contains an error. The function ExistsGroup always returned true. Here is the patch where this is fixed:

[add_support_for_h5link.txt](https://github.com/mannau/h5/files/166852/add_support_for_h5link.txt)

**Comment by mannau** [comment]
Hi Konstantin,
thanks for your suggestions - I have applied your changes. However, they do not pass all tests:

Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  9: FUN(X[[i]], ...)
  10: list.groups(.Object, x, full.names, recursive)
  11: list.groups(.Object, x, full.names, recursive)
  12: stop("Specified path does not exist")
  
  testthat results ================================================================
  OK: 413 SKIPPED: 0 FAILED: 3
  1. Error: DataSet-list-dataset (@test-DataSet.R#151) 
  2. Failure: CommonFG-list-groups (@test-H5Group.R#121) 
  3. Error: CommonFG-list-groups (@test-H5Group.R#129) 
  
  Error: testthat unit tests failed
  Execution halted

Unfortunately I have no more time at the moment to look into this, could you please follow the following steps:
1. fork repo
2. apply changes
3. pull request
That way it is easier for me to integrate your changes and see if all tests run as expected.
I have already created a temporary branch bug-h5link which includes your suggested changes.
Looking forward to your pull-request!

best,
mario
