### ISSUE TITLE
Where do I see the value ["test/testmat"] in my h5 file?

### ISSUE THREAD

**Issue by fabeit** [mannau/h5#35]
Hello,
I am trying to use your package to read an h5 file into a matrix or data.table, I followed your short tutorial but I have no clue in my h5 file what goes into the command for the test/testmat, I think in my file it might not be set, or I don't know how to see it.
dataset_testmat <- file["test/testmat"]

thanks!

ok I think my h5 file doesn't have the same structure as yours. The 'group' information is empty in fact. When I open it in hdfview I have arrays and matrices for all the variables. Is there a way to read all those automatically?

**Comment by mannau** [comment]
Could you specify the structure of file or how it was created?
For example, it should work if the file has been created as follows:

```python
library(h5file)
file <- h5file("test.h5")
file["test/testmat"] <- matrix(1:9, nrow = 3)
h5close(file)
```

--m

Am 24/08/16 um 19:06 schrieb fabeit:
