### ISSUE TITLE
ERROR: compilation failed for package ‘h5’

### ISSUE THREAD

**Issue by slejdops** [mannau/h5#37]
I am getting the following error while installing the h5 package on Ubuntu 12.04.5 LTS ( R version : 3.2.5) and Ubuntu 14.04.5 LTS ( R version : 3.3.1)

`R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('h5', repos='http://cran.rstudio.com/')
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/src/contrib/h5_0.9.8.tar.gz'
Content type 'application/x-gzip' length 393742 bytes (384 KB)
==================================================
downloaded 384 KB

* installing *source* package ‘h5’ ...
** package ‘h5’ successfully unpacked and MD5 sums checked
checking for h5c++... /usr/bin/h5c++
checking for ggrep... /bin/grep
checking whether /bin/grep accepts -o... yes
checking for ggrep... (cached) /bin/grep
checking whether /bin/grep accepts -o... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -I/usr/include   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c Attribute.cpp -o Attribute.o
Attribute.cpp: In function ‘Rcpp::XPtr<H5::Attribute> CreateAttribute_H5File(Rcpp::XPtr<H5::H5File>, std::string, char, Rcpp::NumericVector, int)’:
Attribute.cpp:22:26: error: ‘class H5::H5File’ has no member named ‘createAttribute’
Attribute.cpp: In function ‘Rcpp::XPtr<H5::Attribute> OpenAttribute_H5File(Rcpp::XPtr<H5::H5File>, std::string)’:
Attribute.cpp:116:25: error: ‘class H5::H5File’ has no member named ‘openAttribute’
make: *** [Attribute.o] Error 1
ERROR: compilation failed for package ‘h5’
* removing ‘/usr/local/lib/R/site-library/h5’

The downloaded source packages are in
	‘/tmp/RtmpCMrULN/downloaded_packages’
Warning message:
In install.packages("h5", repos = "http://cran.rstudio.com/") :
  installation of package ‘h5’ had non-zero exit status
> 
`

**Comment by mannau** [comment]
As stated on CRAN the package requires **libhdf5-dev (>= 1.8.12)**. This means that the standard package on Ubuntu 12.04 (1.8.4) and Ubuntu 14.04 (1.8.11) does not work any more.
You can either
1. Install the current Version of HDF5 from source.
2. Upgrade your Ubuntu Version 

Cheers,
Mario

**Comment by slejdops** [comment]
Thank you very much for your help.
