### ISSUE TITLE
could not install h5

### ISSUE THREAD

**Issue by felixmiguelc** [mannau/h5#45]
* installing *source* package ‘h5’ ...
** package ‘h5’ successfully unpacked and MD5 sums checked
checking for h5c++... /usr/bin/h5c++
checking for ggrep... /bin/grep
checking whether /bin/grep accepts -o... yes
checking for ggrep... (cached) /bin/grep
checking whether /bin/grep accepts -o... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=c++0x -I/usr/share/R/include -DNDEBUG -I/usr/include   -I"/.autofs/home/felix/R_Packages/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c Attribute.cpp -o Attribute.o
Attribute.cpp: In function ‘Rcpp::XPtr<H5::Attribute> CreateAttribute_H5File(Rcpp::XPtr<H5::H5File>, std::string, char, Rcpp::NumericVector, int)’:
Attribute.cpp:22:26: error: ‘class H5::H5File’ has no member named ‘createAttribute’
Attribute.cpp: In function ‘Rcpp::XPtr<H5::Attribute> OpenAttribute_H5File(Rcpp::XPtr<H5::H5File>, std::string)’:
Attribute.cpp:116:25: error: ‘class H5::H5File’ has no member named ‘openAttribute’
make: *** [Attribute.o] Error 1
ERROR: compilation failed for package ‘h5’
* removing ‘/.autofs/home/felix/R_Packages/h5’

**Comment by mannau** [comment]
Could you please include:
- Which operating system you are using
- Which HDF5 version

Cheers,
mario

**Comment by felixmiguelc** [comment]
I have
libhdf5-serial-dev 1.8.4-patch1-3ubuntu2
on ubuntu 12.04
Thanks

**Comment by mannau** [comment]
check SystemRequirements on cran.
-m

**Comment by gokceneraslan** [comment]
Does it make sense to check libhdf version in configure script and print an appropriate error message so that people do not file issues about this? The compilation error message is far from intuitive...

**Comment by mannau** [comment]
yes, it does but won't get fixed soon.
