### ISSUE TITLE
Failure to build on macOS Sierra when using homebrew hdf5 version 1.10.1

### ISSUE THREAD

**Issue by marcpaterno** [mannau/h5#48]
The current (very recently updated) version of hdf5 available through Homebrew is hdf5 v1.10.1. In this version, the C++ interface has had several functions removed. For example, the page at https://support.hdfgroup.org/HDF5/doc/ADGuide/Compatibility_Report/CR_1.10.1.html shows that the function `CommonFG::createDataset` has been removed. Some of the removed functions are used by `h5`, and thus compilation fails.

I am willing to try modifying the C++ code in `h5` to match the new interface of hdf5 v1.10.1, if that would be useful. But to do so I would appreciate a pointer to instructions on how to build the package from a cloned repository, either using command-line tools or RStudio.

**Comment by mannau** [comment]
Thanks for the hint!!! Should be fixed now.
But if your motivated, feel free to participate - an RStudio project file is also included now.
Best,
m
