### ISSUE TITLE
Please support VLEN data structures such as ragged arrays

### ISSUE THREAD

**Issue by r-cheologist** [mannau/h5#6]
I am looking for R functionality that would be able to read/extract ragged 
arrays from HDF5 files.

See https://www.hdfgroup.org/HDF5/doc/UG/UG_frame11Datatypes.html :
> 6.4.3.2.3. Variable-length Datatypes
>
> A variable-length (VL) datatype is a one-dimensional sequence of a datatype
> which are not fixed in length from one dataset location to another, i.e.,
> each data element may have a different number of members. Variable-length
> datatypes cannot be divided, the entire data element must be transferred.
> VL datatypes are useful to the scientific community in many different ways, 
> possibly including:
>     Ragged arrays: Multi-dimensional ragged arrays can be implemented with
>     the last (fastest changing) dimension being ragged by using a VL
>     datatype as the type of the element stored.
> ...

**Comment by mannau** [comment]
Should work now - VLEN arrays are mapped to List of vectors.
